first_name = input("Enter your name: ")
last_name = input("Enter your last name: ")
bio_message = input("Enter your bio here: ").strip()
username = first_name[0].lower()+last_name.lower()
full_name = first_name.title() + " " + last_name.title()
l = len(bio_message)
r = bio_message.replace("I am" , "I'm")

print(f"{first_name}")
print(f"{last_name}")
print(f"{username}")
print(f"{full_name}")
print(f"{l}")
print(f"{r}")
